In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
raw_data = pd.read_csv('../../DataSets/sangamiitmadras/Sangam_2019_Hackathon_Data.csv')

In [8]:
raw_data.shape  # 34 int,float columns and 5 columns are categorical

(1048575, 39)

In [9]:
raw_data.describe()

,S.no,latitude,longitude,humidity,temperature,heat_index,uv,luminence,ir,accx,...,ch4,h2,c2h5o4,pm01,pm25,pm10,pressure,draft,air_temp,air_speed
count,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,...,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,5.549364e+05,1.726731e+10,1.896300e+10,5.847379e+01,3.311036e+01,1.054308e+02,2.083207e+00,4.538108e+02,8.141401e+02,-5.230708e+02,...,1.525667e+07,1.858352e+01,2.363607e+01,5.628084e+01,1.492431e+02,1.608585e+02,1.810081e+00,3.853857e+00,9.785538e+00,5.688758e-02
std,3.199438e+05,5.866550e+11,5.956350e+11,2.561486e+01,7.415426e+00,1.918676e+03,3.254922e+01,3.212809e+03,3.538145e+03,2.670664e+03,...,5.249482e+08,3.678936e+01,2.939894e+01,1.623200e+02,3.363523e+02,3.349206e+02,4.300660e+00,7.970380e+00,2.412219e+01,1.377303e+00
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.964410e+06,0.000000e+00,0.000000e+00,0.000000e+00,-3.276800e+04,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-5.000000e+01,0.000000e+00
25%,2.765865e+05,1.299080e+01,7.703400e+01,3.900000e+01,3.180000e+01,9.615000e+01,2.000000e-02,2.610000e+02,2.530000e+02,0.000000e+00,...,2.241780e+03,1.230000e+00,2.550000e+00,1.300000e+01,1.900000e+01,2.600000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,5.565130e+05,1.310440e+01,7.703400e+01,5.800000e+01,3.330000e+01,1.060000e+02,3.000000e-02,2.620000e+02,2.550000e+02,0.000000e+00,...,2.650140e+06,2.299000e+01,3.154000e+01,2.300000e+01,3.300000e+01,4.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,8.344905e+05,2.845800e+01,8.017100e+01,7.840000e+01,3.560000e+01,1.186600e+02,9.000000e-02,2.740000e+02,3.840000e+02,0.000000e+00,...,3.924150e+06,2.703000e+01,3.627000e+01,4.000000e+01,6.300000e+01,8.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,1.103661e+06,2.020000e+13,2.020000e+13,1.203200e+03,8.448000e+02,2.645200e+02,6.553500e+02,6.553500e+04,6.553500e+04,3.240800e+04,...,2.820000e+11,2.705830e+03,1.937770e+03,1.200000e+03,1.200000e+03,1.200000e+03,2.480000e+02,1.520000e+02,1.500000e+02,7.500000e+01

In [10]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 39 columns):
S.no           1048575 non-null int64
device_id      1045651 non-null object
latitude       1048575 non-null float64
nso            1043739 non-null object
longitude      1048575 non-null float64
ewo            1043739 non-null object
svrtime        1048575 non-null object
timestamp      1048575 non-null object
humidity       1048575 non-null float64
temperature    1048575 non-null float64
heat_index     1048575 non-null float64
uv             1048575 non-null float64
luminence      1048575 non-null float64
ir             1048575 non-null float64
accx           1048575 non-null float64
accy           1048575 non-null float64
accz           1048575 non-null float64
acctemp        1048575 non-null float64
gyrox          1048575 non-null float64
gyroy          1048575 non-null float64
gyroz          1048575 non-null float64
so2_tmp        1048575 non-null float64
so2_gas        1048575 non-null float64
so2_conc       1048575 non-null float64
nh3            1048575 non-null float64
co             1048575 non-null float64
no2            1048575 non-null float64
c3h8           1048575 non-null float64
c4h10          1048575 non-null float64
ch4            1048575 non-null float64
h2             1048575 non-null float64
c2h5o4         1048575 non-null float64
pm01           1048575 non-null float64
pm25           1048575 non-null float64
pm10           1048575 non-null float64
pressure       1048575 non-null float64
draft          1048575 non-null float64
air_temp       1048575 non-null float64
air_speed      1048575 non-null float64
dtypes: float64(33), int64(1), object(5)
memory usage: 312.0+ MB

In [12]:
raw_data.isnull().sum()

S.no              0
device_id      2924
latitude          0
nso            4836
longitude         0
ewo            4836
svrtime           0
timestamp         0
humidity          0
temperature       0
heat_index        0
uv                0
luminence         0
ir                0
accx              0
accy              0
accz              0
acctemp           0
gyrox             0
gyroy             0
gyroz             0
so2_tmp           0
so2_gas           0
so2_conc          0
nh3               0
co                0
no2               0
c3h8              0
c4h10             0
ch4               0
h2                0
c2h5o4            0
pm01              0
pm25              0
pm10              0
pressure          0
draft             0
air_temp          0
air_speed         0
dtype: int64

In [13]:
raw_data.head()

,S.no,device_id,latitude,nso,longitude,ewo,svrtime,timestamp,humidity,temperature,...,ch4,h2,c2h5o4,pm01,pm25,pm10,pressure,draft,air_temp,air_speed
0,1,S5,28.4578,N,77.034,E,4/23/2019 19:50,4/19/2023 19:50,41.0,33.2,...,3852370.0,26.62,36.03,62.0,75.0,86.0,0.0,0.0,0.0,0.0
1,2,S3,28.4579,N,77.034,E,4/23/2019 19:50,4/19/2023 19:50,95.0,33.5,...,5163570.0,30.04,39.99,62.0,77.0,92.0,0.0,0.0,0.0,0.0
2,3,S4,28.4579,N,77.034,E,4/23/2019 19:50,4/19/2023 19:50,0.0,0.0,...,2912570.0,23.72,32.62,51.0,67.0,82.0,0.0,0.0,0.0,0.0
3,4,S5,28.4578,N,77.034,E,4/23/2019 19:51,4/19/2023 19:50,41.0,33.3,...,3997190.0,27.03,36.51,63.0,76.0,85.0,0.0,0.0,0.0,0.0
4,5,S3,28.4579,N,77.034,E,4/23/2019 19:51,4/19/2023 19:50,95.0,33.5,...,5258110.0,30.26,40.25,61.0,77.0,95.0,0.0,0.0,0.0,0.0

In [62]:
#raw_data.nso.value_counts()

In [67]:
raw_data[raw_data.nso.isnull()].device_id.value_counts()

{"success":1    1912
Name: device_id, dtype: int64

In [ ]:
# (10,48,575, 39)

#S.no              0
#device_id      2924
#latitude          0
#nso            4836
#longitude         0
#ewo            4836

In [70]:
raw_data.device_id.value_counts()

S1              201826
M5              122410
S10             119691
S5              113304
S8              107629
S4               95594
S9               88382
S3               77241
M6               44437
M3               27048
S6               15323
M1               13992
S7                9835
M4                5558
{"success":1      1912
M7                 765
M2                 696
S81                  8
Name: device_id, dtype: int64

In [72]:
raw_data.columns

Index(['S.no', 'device_id', 'latitude', 'nso', 'longitude', 'ewo', 'svrtime',
       'timestamp', 'humidity', 'temperature', 'heat_index', 'uv', 'luminence',
       'ir', 'accx', 'accy', 'accz', 'acctemp', 'gyrox', 'gyroy', 'gyroz',
       'so2_tmp', 'so2_gas', 'so2_conc', 'nh3', 'co', 'no2', 'c3h8', 'c4h10',
       'ch4', 'h2', 'c2h5o4', 'pm01', 'pm25', 'pm10', 'pressure', 'draft',
       'air_temp', 'air_speed'],
      dtype='object')

In [76]:
raw_data.loc[:,['pm01','pm25','pm10']]

         pm01  pm25  pm10
0        62.0  75.0  86.0
1        62.0  77.0  92.0
2        51.0  67.0  82.0
3        63.0  76.0  85.0
4        61.0  77.0  95.0
5        52.0  67.0  79.0
6        61.0  77.0  98.0
7        53.0  68.0  81.0
8        62.0  75.0  84.0
9        56.0  72.0  88.0
10       62.0  75.0  85.0
11       62.0  78.0  95.0
12       56.0  72.0  85.0
13       63.0  76.0  85.0
14       62.0  79.0  91.0
15       61.0  74.0  83.0
16       53.0  66.0  81.0
17       64.0  80.0  94.0
18       60.0  74.0  86.0
19       52.0  67.0  83.0
20       64.0  80.0  93.0
21       60.0  72.0  81.0
22       52.0  67.0  83.0
23       64.0  80.0  96.0
24       60.0  73.0  83.0
25       53.0  68.0  83.0
26       61.0  75.0  92.0
27       61.0  74.0  88.0
28       54.0  68.0  83.0
29       62.0  77.0  93.0
...       ...   ...   ...
1048545   9.0  13.0  19.0
1048546  11.0  16.0  22.0
1048547  12.0  17.0  24.0
1048548  11.0  16.0  21.0
1048549  11.0  16.0  23.0
1048550  16.0  24.0  34.0
1048551   8.0  13.0  19.0
1048552  10.0  15.0  18.0
1048553  15.0  23.0  33.0
1048554  11.0  16.0  21.0
1048555  10.0  14.0  20.0
1048556  14.0  18.0  23.0
1048557  14.0  18.0  25.0
1048558  11.0  17.0  23.0
1048559  13.0  18.0  25.0
1048560  12.0  17.0  23.0
1048561  14.0  19.0  26.0
1048562  19.0  28.0  40.0
1048563  13.0  18.0  26.0
1048564  14.0  18.0  26.0
1048565  40.0  57.0  80.0
1048566  10.0  14.0  20.0
1048567  14.0  20.0  26.0
1048568  21.0  31.0  44.0
1048569   8.0  13.0  19.0
1048570  13.0  19.0  25.0
1048571  30.0  46.0  65.0
1048572   8.0  13.0  19.0
1048573  11.0  15.0  21.0
1048574  22.0  31.0  44.0

[1048575 rows x 3 columns]

In [78]:
pd.date_range("20180101",periods=5).

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='D')

latitude == Latitude of the location at which data was collected.
longitude == Longitude of the location at which data was collected.
humidity == Ambient relative humidity value obtained from the temperature and humidity sensor. Unit: %
temperature == Ambient temperature value obtained from the temperature and humidity sensor. Unit: Degree Celcius
heat_index == Heat index value obtained from temperature and humidity sensor. It can be derived from Temperature and Humidity values. Unit: No units

uv == UV index obtained from the light sensors. UV index is a linear scale which indicates the severity of the UV exposure. The lowest value is 0 and the highest value is 10. Unit: No units

luminence == Ambient light intensity. Unit: Lux

ir == Infrared intensity. Unit: Lux


Accelerometer and Gyroscope - It a 6 degree of freedom(DoF) accelerometer device (MPU6050)

accx == Raw acceleration in X direction

accy == Raw acceleration in Y direction

accz == Raw acceleration in Z direction

acctemp == Temperature reading obtained from MPU6050

gyrox == Raw gyroscope orientation in X drection

gyroy == Raw gyroscope orientation in Y drection

gyroz == Raw gyroscope orientation in Z direction

so2_tmp == Temperature reading obtained from SPEC SO2 sensor

https://www.spec-sensors.com/wp-content/uploads/2016/10/ULPSM-SO2-968-006.pdf

so2_gas

Raw voltage values from SO2 sensor. Unit: mV

so2_conc

SO2 concentration. Unit: ppm. Note: For details on the conversion from raw voltage to SO2 concentration, please refer to the data sheet of SPEC SO2 sensor

nh3

Ammonia concentration as obtained by Multichannel gas sensor. Unit: ppm

http://wiki.seeedstudio.com/Grove-Multichannel_Gas_Sensor/

co

Carbon Monoxide concentraion as obtained by Multichannel gas sensor. Unit: ppm

no2

Nitrogen di-oxide concentraion as obtained by Multichannel gas sensor. Unit: ppm

c3h8

Propane concentraion as obtained by Multichannel gas sensor. Unit: ppm

c4h10

Iso Butane concentraion as obtained by Multichannel gas sensor. Unit: ppm

ch4

Methane concentraion as obtained by Multichannel gas sensor. Unit: ppm

h2

Hydrogen concentraion as obtained by Multichannel gas sensor. Unit: ppm

c2h5o4

Ethanol concentraion as obtained by Multichannel gas sensor. Unit: ppm

pm01

PM 01 concentration. Unit: ug/cc

 
pm25

PM 01 concentration. Unit: ug/cc

 
pm10

PM 01 concentration. Unit: ug/cc

 
pressure

Differential Pressure (Pa) at the sensor.

This sensor(MPXV7002 series) measures the relative air speed at the device using differential pressure. https://www.nxp.com/docs/en/data-sheet/MPXV7002.pdf

draft

Draft

air_temp

Air Temperature(Deg C)