In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use("fivethirtyeight")

import seaborn as sns
import matplotlib.ticker as ticker

import folium as f

In [3]:
raw_data = pd.read_csv('../../DataSets/sangamiitmadras/saaf_data.csv')

In [4]:
raw_data.head()

,device_id,latitude,nso,longitude,ewo,svrtime,timestamp,humidity,temperature,heat_index,...,ch4,h2,c2h5o4,pm01,pm25,pm10,pressure,draft,air_temp,air_speed
0,S5,28.4578,N,77.034,E,2019-04-23 19:50:00,2019-04-23 19:50:00,41.000000,33.200000,93.79000,...,3852370.0,26.62,36.03,62.0,75.0,86.0,0.0,0.0,0.0,0.0
1,S3,28.4579,N,77.034,E,2019-04-23 19:50:00,2019-04-23 19:50:00,95.000000,33.500000,138.48000,...,5163570.0,30.04,39.99,62.0,77.0,92.0,0.0,0.0,0.0,0.0
2,S4,28.4579,N,77.034,E,2019-04-23 19:50:00,2019-04-23 19:50:00,39.926335,33.350173,94.78934,...,2912570.0,23.72,32.62,51.0,67.0,82.0,0.0,0.0,0.0,0.0
3,S5,28.4578,N,77.034,E,2019-04-23 19:51:00,2019-04-23 19:50:00,41.000000,33.300000,94.09000,...,3997190.0,27.03,36.51,63.0,76.0,85.0,0.0,0.0,0.0,0.0
4,S3,28.4579,N,77.034,E,2019-04-23 19:51:00,2019-04-23 19:50:00,95.000000,33.500000,138.48000,...,5258110.0,30.26,40.25,61.0,77.0,95.0,0.0,0.0,0.0,0.0